name: Fast Forward Staging to Main on Buffer PR Merge

on:
  pull_request:
    types: [closed]

jobs:
  fast-forward:
    if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'buffer'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: 'buffer'

      - name: Configure Git
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"

      - name: Fetch all branches
        run: git fetch --all

      - name: Fast-forward target branch
        run: |
          git checkout main
          git merge --ff-only staging
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

